import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ApiProvider } from "@/context/ApiContext";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { CartProvider } from "@/context/CartContext";
import PizzaLoader from "./Components/Loader";
import { LoadingProvider } from "@/context/LoadingContext";

const robotoMono = Roboto_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${robotoMono.variable} antialiased flex flex-col min-h-screen`}>
        <LoadingProvider>
        <CartProvider>
          <ApiProvider>
            <Navbar />
            <PizzaLoader />
            {/* Main content, för att lägga footern längst ner */}
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </ApiProvider>
        </CartProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}