name: Cypress Tests

on:
  pull_request:
    branches:
      - main  # Kör Cypress på PR:er mot main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --headless
        env:
          BASE_URL: "https://pizzalover-g7fnhxctfsfbe6c7.westeurope-01.azurewebsites.net/"  # Din staging-miljö

      - name: Upload Cypress failure artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/screenshots/
